name: Java 17 Maven Build and Test

on: push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set Java version
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 17

      - name: Build
        run: ./mvnw clean package spring-boot:repackage

        uses: actions/upload-artifact@v3
        with:
          name: auth_service
          path: src/target

  run_test:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set Java version
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 17

      - name: run target
      - uses: actions/download-artifact@v3
        with:
          name: auth_service
          path: src/target
        run: |
          java -jar target/jwt-auth-service-1.0.0.jar
